# Generated by Django 4.1.5 on 2023-07-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
