# Generated by Django 4.1.5 on 2023-07-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_venta_saledetail_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_percentage',
        ),
    ]
