# Generated by Django 4.1.5 on 2023-07-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_tax_amount_remove_sale_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
