# Generated by Django 4.1.5 on 2023-07-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_old_balance'),
        ('sales', '0005_sale_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Beginning Balance', 'Beginning Balance'), ('Sale', 'Sale'), ('Party To Party [Received]', 'Party To Party [Received]'), ('Ending Balance', 'Ending Balance')], max_length=40)),
                ('invoice_bill_no', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receivable_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='customers.customer')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
    ]
