# Generated by Django 4.1.5 on 2023-07-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
