# Generated by Django 4.1.5 on 2023-08-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_transaction_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='unit',
            field=models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Doz', 'Doz')], max_length=20, null=True),
        ),
    ]
